# Generated by Django 4.0.6 on 2022-07-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_rn', models.CharField(max_length=100)),
                ('std_name', models.CharField(max_length=100)),
                ('std_address', models.CharField(max_length=100)),
                ('std_study_pro', models.CharField(max_length=100)),
            ],
        ),
    ]
