# Generated by Django 4.0.6 on 2022-07-19 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=100)),
                ('book_pages', models.IntegerField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateTimeField(default=datetime.datetime(2022, 7, 27, 17, 37, 24, 787177))),
                ('remarks', models.CharField(default='Some Remarks', max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.students')),
            ],
        ),
    ]
